title: Shashank Rallapalli
logo: /assets/headshot.jpeg
description: Data Analyst, skillful in managing and breaking down large volumes of information. Proactive at heading off issues in operations, workflow and production by uncovering trends affecting business success. Proven expertise in developing predictive analytics applications, building interactive dashboards, and implementing machine learning models to optimize business processes and enhance decision-making. 
#show_downloads: true
theme: jekyll-theme-minimal
